// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWLB7BAEcPX-lTrSFk7Ev8TD4dqTudt8I',
    appId: '1:856875474030:web:56b389dd0aba2ae7b01a7f',
    messagingSenderId: '856875474030',
    projectId: 'lottologin-bfd3e',
    authDomain: 'lottologin-bfd3e.firebaseapp.com',
    storageBucket: 'lottologin-bfd3e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbPiYkcKNucgY2JPAcXxOsQMltQtHe_I8',
    appId: '1:856875474030:android:9eb0e132f5cbd760b01a7f',
    messagingSenderId: '856875474030',
    projectId: 'lottologin-bfd3e',
    storageBucket: 'lottologin-bfd3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfClXwia1gIBK6Lye6_XZzJqMREvS2jM4',
    appId: '1:856875474030:ios:7b5ffc954f931e56b01a7f',
    messagingSenderId: '856875474030',
    projectId: 'lottologin-bfd3e',
    storageBucket: 'lottologin-bfd3e.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfClXwia1gIBK6Lye6_XZzJqMREvS2jM4',
    appId: '1:856875474030:ios:7b5ffc954f931e56b01a7f',
    messagingSenderId: '856875474030',
    projectId: 'lottologin-bfd3e',
    storageBucket: 'lottologin-bfd3e.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWLB7BAEcPX-lTrSFk7Ev8TD4dqTudt8I',
    appId: '1:856875474030:web:e09978a702da5aa2b01a7f',
    messagingSenderId: '856875474030',
    projectId: 'lottologin-bfd3e',
    authDomain: 'lottologin-bfd3e.firebaseapp.com',
    storageBucket: 'lottologin-bfd3e.firebasestorage.app',
  );
}
